# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseACLEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('controller_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('access_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('access_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('doors', models.ManyToManyField(to='jba_core.Door')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleRecurringPattern',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_time', models.TimeField()),
                ('until_time', models.TimeField()),
                ('days_of_week', models.CharField(max_length=255)),
                ('days_of_month', models.CharField(max_length=255)),
                ('months', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonACLEntry',
            fields=[
                ('baseaclentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jba_core.BaseACLEntry')),
            ],
            bases=('jba_core.baseaclentry',),
        ),
        migrations.CreateModel(
            name='RoleACLEntry',
            fields=[
                ('baseaclentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jba_core.BaseACLEntry')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jba_core.Role')),
            ],
            bases=('jba_core.baseaclentry',),
        ),
        migrations.AddField(
            model_name='simplerecurringpattern',
            name='acl',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jba_core.BaseACLEntry'),
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(to='jba_core.Role'),
        ),
        migrations.AddField(
            model_name='key',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jba_core.Person'),
        ),
        migrations.AddField(
            model_name='controller',
            name='doors',
            field=models.ManyToManyField(to='jba_core.Door'),
        ),
        migrations.AddField(
            model_name='baseaclentry',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jba_core.Place'),
        ),
        migrations.AddField(
            model_name='personaclentry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jba_core.Person'),
        ),
    ]
